### ISSUE TITLE
Version 2.0.0 is not Java6 compatible

### ISSUE THREAD

**Issue by raspy** [boxheed/gradle-sweeney-plugin#19]
Maybe this is intentional, but Gradle itself is still supported on Java6, so plugins should not require newer Java versions.

**Comment by boxheed** [comment]
The requirement for Java 7 is intentional and I disagree that plugins should support Java 6 just because the framework does, yes you may be restricting who can use your plugin, but there are other reasons not to support Java 6 that are more compelling than it should be supported just because the framework does.  I had a quick look at some of my favorite Gradle plugins developed by the Nebula team and they are only compatible with Java 7, so I am not alone and am not going to move this to Java 6 for this reason alone.

**Comment by raspy** [comment]
I understand your point of view. Actually I tried to use your plugin to enforce Java7 usage, since there are statements in build script that require Java7. I thought I could use the plugin to handle Java version check gracefully so that Gradle does not fail with stacktrace, but since plugin itself is Java7 only, it fails immediately with another error (not necessarily meaningful to users):

A problem occurred evaluating root project 'app'.
> java.lang.UnsupportedClassVersionError: com/fizzpod/gradle/plugins/sweeney/SweeneyPlugin : Unsupported major.minor version 51.0

So my use case to require Java7 seems to work accidentally, but this is no longer graceful :-)

Of course it is your decision how to go with the plugin, but this particular use case (which is also mentioned as an example in README) to check for jdk1.7 is not feasible with 2.0.0 version.
