### ISSUE TITLE
how to run the plugin?

### ISSUE THREAD

**Issue by Kingson4Wu** [boxheed/gradle-sweeney-plugin#21]
` gradle sweeney`? no task named 'sweeney'

**Comment by boxheed** [comment]
@Kingson4Wu there is no task for this plugin, if you have defined your rules in your build script then they are automatically run as part of the appropriate phase.

**Comment by Kingson4Wu** [comment]
how to define a rule to check whether there contains multiple  class with the same name  in the project？

**Comment by boxheed** [comment]
So there are a few options but none of the built in rules will do that out of the box however...

All of the rules support the generation of the 'value' using a closure so you could use an equals or boolean rule with your own code in the closure to check for duplicate class names and return true or false in the case of a boolean rule or some other object in the case of an equals rule. Have a go  with that, one of the examples shows the use of a closure to get at a system property.

The other options are

1. The plugin supports injecting of custom rules however this isn't documented yet and I am currently travelling with only my phone to respond with so won't be able to write it up for a week or so. 

2. Contribute a new rule to be included in the standard distribution with a pull request. But again I am traveling so won't be able to look at a pull request until I get back.

Let me know how you get on

**Comment by boxheed** [comment]
@Kingson4Wu have you solved your problem?

**Comment by Kingson4Wu** [comment]
> @Kingson4Wu have you solved your problem?
Unfortunately no, my poblem is 
https://stackoverflow.com/questions/57380320/gradle-how-to-check-duplicate-class-in-project

**Comment by boxheed** [comment]
so you are having a clash between the name of a class in a third party library and a class of your own, is the class declaration exactly the same i.e. is your own class in the same package aswell as having the same package name?

**Comment by Kingson4Wu** [comment]
> @Kingson4Wu so you are having a clash between the name of a class in a third party library and a class of your own, is the class declaration exactly the same i.e. is your own class in the same package aswell as having the same class name?

yes.Not that I did it on purpose, but other developers add the same class in a third party library.

**Comment by boxheed** [comment]
So in order to find clashing classes it would have to scan the different classpaths i.e. the compile, test and runtime ones and compare them to what is in the source tree.

From what you've described it sounds like there is a difference between the compile and test classpaths and what is available at runtime. Also given how classloaders work in Java and the different types of ClassLoaders used by different frameworks/containers there is a lot of variation. Add in that if you're compiling against interfaces then the implementations tend not to get pulled into compile time classpaths, this is especially true if you are building an application against interfaces e.g. applications to be deployed into a servlet containers.

I can have a look at implementing something if you point me at the project so that there is a good example, but to be honest what you describe is better found with a good CI/CD pipeline.

**Comment by boxheed** [comment]
Just reviewing the issues. This has been open for a number of years so assume the help is no longer needed. Closing this issue
